### ISSUE TITLE
Document database assumptions for server

### ISSUE THREAD

**Issue by spuder** [cvent/octopus-deploy-cookbook#105]
I'm a bit confused on how the database is set up. The readme shows that you can use `create_database` property to setup the database, but it assumes a database sever is already installed. 

Looking at appvoyer and travis, I don't see how you are testing the octopus server. The connection string is

    'Data Source=localhostdba;Initial Catalog=octo;Integrated Security=False;User ID=octo;Password=password'

Yet nowhere is sql installed. Are you using a golden image with sql express already installed? I can't get the server cookbook to converge without an actual database to point to.

**Comment by spuder** [comment]
AppVoyer now connects to a database

https://github.com/cvent/octopus-deploy-cookbook/commit/32a78cc03824062031bbef147f2397afc856730d

The connection string I've had luck with

```ruby
connection_string "Server=(local)\\SQLEXPRESS;Database=FOOBAR;Trusted_Connection=True"
```

**Comment by brentm5** [comment]
Local testing still doesn’t install sqlserver. Might need to roll this into the test cookbook for local testing so that we can install sql server. Currently local test kitchen does not work.
