### ISSUE TITLE
Net::HTTPServerException: 403 "Forbidden" during tentacle installation

### ISSUE THREAD

**Issue by pinterl** [cvent/octopus-deploy-cookbook#121]
When I execute the `octopus_deploy_tentacle 'Tentacle' do` block I get the error message:

>
>            Error executing action `install` on resource 'octopus_deploy_tentacle[Tentacle]'
>
>            Net::HTTPServerException
>            ------------------------
>            remote_file[C:\Users\XXX\AppData\Local\Temp\kitchen\cache/octopus-tentacle.msi] (C:/Users/XXX/AppData/Local/Temp/kitchen/cache/cookbooks/octopus-deploy/resources/tentacle.rb line 59) had an error: Net::HTTPServerException: 403 "Forbidden"
> 
>            Resource Declaration:
>            ---------------------
>            # In C:/Users/XXX/AppData/Local/Temp/kitchen/cache/cookbooks/umg_octopus/recipes/tentacle.rb
> 
>             24: octopus_deploy_tentacle 'Tentacle' do
>             25:   action [:install, :configure]
>             26:   version "#{node['umg_octopus']['version']}"
>             27:   # checksum "#node['umg_octopus']['checksum']"
>             28:   server "#{node['umg_octopus']['server']}"
>             29:   trusted_cert "#{node['umg_octopus']['trusted_cert']}"
>             30:   # You can enable this resource to update firewall rules as well
>             31:   configure_firewall true
>             32: end
>             33:
> 
>            Compiled Resource:
>            ------------------
>            # Declared in C:/Users/XXX/AppData/Local/Temp/kitchen/cache/cookbooks/umg_octopus/recipes/tentacle.rb:24:in `from_file'
> 
>            octopus_deploy_tentacle("Tentacle") do
>              action [:install, :configure]
>              retries 0
>              retry_delay 2
>              default_guard_interpreter :default
>              declared_type :octopus_deploy_tentacle
>              cookbook_name "umg_octopus"
>              recipe_name "tentacle"
>              version "3.17.6"
>              server "MY SERVER IP"
>              trusted_cert "MY SERVER CERTIFICATE"
>              configure_firewall true
>              upgrades_enabled true
>            end

The generated value of install_url = https://download.octopusdeploy.com/octopus/Octopus.Tentacle.3.17.6-x64.msi

When I use my browser to go to the same address, I also get the "Access Denied" message.
Is this the correct download URL? Recently the Octopus website directed me to https://octopus.com/downloads/3.17.6

**Comment by brentm5** [comment]
@pinterl this is actually not a bug, a little while ago the octopus deploy team decoupled the tentacle from the server version The latest version of the tentacle is version 3.16.0

You can read more here:

https://octopus.com/blog/octopus-release-3-14#tentacle-split
