### ISSUE TITLE
Setting tentacle_name does not seem to have any effect

### ISSUE THREAD

**Issue by reidca** [cvent/octopus-deploy-cookbook#139]
Setting the tentacle_name property in the recipe does not appear to do anything in Octopus.
I had assumed that the tentacle_name is akin to the "Display Name" in Octopus however after setting it the display name still uses the IP address of the instance rather than what was set in the tentacle_name.

What is the Name attribute ? Is this the display name instead? It's not clear from the docs.

**Comment by spuder** [comment]
If you don't set `tentacle_name` it defaults to the chef `node.name`

https://github.com/cvent/octopus-deploy-cookbook/blob/master/resources/tentacle.rb#L45

What version of the cookbook? The tentacles are registered properly for me in my environment. Could you show a redacted resource that you are using in your cookbook? 

![screenshot 2018-03-19 13 21 15](https://user-images.githubusercontent.com/242382/37617333-7a215414-2b78-11e8-93a3-6068198b0483.png)
![screenshot 2018-03-19 13 22 03](https://user-images.githubusercontent.com/242382/37617347-86c58ffa-2b78-11e8-8b08-09f250bca0e8.png)

**Comment by reidca** [comment]
Thank you for responding. 

The issue was the cookbook was out of date. It would be useful to know which configuration is valid for which version. I was using the property but as the cookbook was out of date it was just ignoring the property.

Also, how are you able to understand which of the properties is for which action? e.g. is tentacle_name for register or install action? I have worked this out now but it would be useful to understand it from the documentation. 

Forgive me if this is obvious, I am very new to chef so maybe missing something.

Thanks

**Comment by spuder** [comment]
Glad you figured it out. Currently you could look at the resource and see which property is used where

https://github.com/cvent/octopus-deploy-cookbook/blob/master/resources/tentacle.rb

**Comment by reidca** [comment]
Thanks.
Last question...what's the difference between 'instance' and 'tentacle_name' ?

**Comment by spuder** [comment]
The instance is if you have multiple tentacles installed simutaniously (which very few people do). It defaults to the instance name of 'Tentacle'

https://github.com/cvent/octopus-deploy-cookbook/blob/master/resources/tentacle.rb#L26

tentacle_name is the actual name of the tentacle as it shows up in the octopus gui

It defaults to the chef node.name

https://github.com/cvent/octopus-deploy-cookbook/blob/master/resources/tentacle.rb#L45
