### ISSUE TITLE
Why this cookbook?

### ISSUE THREAD

**Issue by spuder** [cvent/octopus-deploy-cookbook#26]
I've found 3 cookbooks to deploy octopus tentacles

https://github.com/cvent/octopus-deploy-cookbook

https://github.com/burnzy/octopus-cookbook

https://github.com/ashmere/octopusdeploy-chef

Why this one? Whats different from the others?

**Comment by bigbam505** [comment]
@spuder 

Its all personal preference to be honest.  This is the second iteration and what we use internally here to install tentacles / manage our octo servers (although the server management is not 100% complete at the moment).  This cookbook uses resources to install tentacles / services (which is the pattern Chef is pushing towards).  It's opinionated but open to suggestions from the community.  Also most of the cookbooks are outdated and some aren't even on supermarket which makes using them harder.  We test this cookbook both internally and in kitchen on every PR so we are very much about accuracy here.

Hope this helps in your quest.

**Comment by spuder** [comment]
Thanks for the info.

**Comment by bigbam505** [comment]
No problem.
