### ISSUE TITLE
Looking forward for configuration bits :)

### ISSUE THREAD

**Issue by Tazer** [cvent/octopus-deploy-cookbook#3]
Noticed your post on: http://help.octopusdeploy.com/discussions/questions/5675-installing-octopus-deploy-with-chef

**Comment by Tazer** [comment]
Think you will need to check this one:  http://g.octopushq.com/CryptoRequiresUserProfile 

Tried some with powershell before, but got into problem when running via winrm and chef.

**Comment by bigbam505** [comment]
@Tazer configuring the tentacle has been added. Try out the `:configure` action on the tentacle resource.

**Comment by brentm5** [comment]
@Tazer we now have some configuration of octopus deploy tentacles and servers.  Hope this helps you out!
