### ISSUE TITLE
Warn if octopus server is unavailable

### ISSUE THREAD

**Issue by spuder** [cvent/octopus-deploy-cookbook#38]
Enhancement

Add a powershell_script resource that attempts to call the octopus server api. 
If the octopus api is unavailable, log a warning and continue with the chef run. 
- only if api_key is defined
- only if server is defined
- only in :register resource, or any other resource where the api is used.

**Comment by spuder** [comment]
Closing because non trivial to implement, and has limited benefit.

**Comment by brentm5** [comment]
I do not particularly like this idea of making this a script but because this means it runs every time and shows up as a resource ran which means it is not very idempotent.  One thing that we could do is use the http client in chef to make a test call and skip if can not reach the server.  

```ruby
# Use the chef internal http client to check the octopus deploy endpoint is valid.
Chef::HTTP.new('https://octopus_endpoint/').get('/api')
```

**Comment by spuder** [comment]
I like this. The cookbook could do a :before notify on the register resource, that way it isn't calling the api every chef run. Unfortunately :before was introduced in chef 12.6.
I blogged a while ago about how to emulate the :before behavior on chef clients 12.0 - 12.5
http://spuder.github.io/2015/chef-taste-tester-pattern/

My vote is to not implement this feature since users will get an error any way if the octopus server is unavailable. It would be a fair amount of work that really is only solving a cosmetic problem (cause of error message is hard to infer).

**Comment by brentm5** [comment]
I was thinking something about using this in the compile phase in a try catch block and if the endpoint failed to load it would simply skip the register and log or something.

**Comment by spuder** [comment]
I stepped on this 💣  again today. 

Simply looking at `/api/environments/all` and comparing it to the current environment using ::Json should be sufficient. 

https://github.com/OctopusDeploy/OctopusDeploy-Api/wiki/Environments

**Comment by brentm5** [comment]
I don't like the idea of hitting two endpoint each time we want to join a machine to an environment.  I think this just means we should include better error handling for the cases where a register fails.
