### ISSUE TITLE
Make tentacle install msi more quiet

### ISSUE THREAD

**Issue by spuder** [cvent/octopus-deploy-cookbook#51]
When you run chef-client and install the tentacle, the msi pops open a progress bar. 

![screenshot 2016-08-16 14 15 40](https://cloud.githubusercontent.com/assets/242382/17714281/54eb06c0-63bc-11e6-9815-2735369a4779.png)

The fix is to add the `/quiet` parameter to the msi

    msiexec /i Octopus.Tentacle.<version>.msi /quiet

http://docs.octopusdeploy.com/display/OD/Automating+Tentacle+installation

**Comment by brentm5** [comment]
Well that sucks.  Ill fix this in a few

**Comment by brentm5** [comment]
Fixed in v0.6.2
