### ISSUE TITLE
Tentacle Checksum doesn't work as expected (or isn't documented correctly)

### ISSUE THREAD

**Issue by mhudson** [cvent/octopus-deploy-cookbook#75]
Using the cookbook to download tentacle from https://octopus.com/downloads:
https://download.octopusdeploy.com/octopus/Octopus.Tentacle.3.5.2-x64.msi

MD5 checksum taken from same website:
8b0ca3cfa5ecde120081aeb070c8b585

Chef::Exceptions::ChecksumMismatch: Checksum on resource (8b0ca3) does not match checksum on content (706bcc)

Either Octopus got it wrong, or the MD5 checksum provided isn't right?

**Comment by brentm5** [comment]
Checksums in Chef use sha 256.  You can find out what the checksum for a file is on a mac by running this:

```
shasum -a 256 <filename>
```

**Comment by mhudson** [comment]
Thanks Brent. One obvious problem is that the SHA256 should come from the verified owner of the downloaded file... ie Octopus! They give us an MD5 which doesn't suit Chef. Do you know some at Octopus to ask them to provide a SHA256 too? MH

**Comment by brentm5** [comment]
You could still verify that the md5 hash is correct by downloading the file locally first.  Then you can find the sha256 and verify its the correct file and use that value.  Its one bit of manual steps however but should take a relatively short time for now.  If its important to have octopus deploy provide the sha256 maybe you can reach out to their support to try and see if they would provide additional shas on their download pages.

**Comment by webframp** [comment]
I'm interested in this as well, added to their Uservoice: https://octopusdeploy.uservoice.com/forums/170787-general/suggestions/17265596-provide-sha256-sums-for-downloads-not-just-md5
