### ISSUE TITLE
Argument Error with Chef 13.

### ISSUE THREAD

**Issue by budgester** [cvent/octopus-deploy-cookbook#88]
ArgumentError
-------------
Cannot specify both default and name_property/name_attribute together on property path of resource octopus_deploy_tools

System Info:
------------
chef_version=13.0.118
platform=windows
platform_version=6.3.9600
ruby=ruby 2.4.1p111 (2017-03-22 revision 58053) [x64-mingw32]
program_name=C:/opscode/chef/bin/chef-client
executable=C:/opscode/chef/bin/chef-client

**Comment by brentm5** [comment]
@budgester Can you also include the resource block that was used?

**Comment by brentm5** [comment]
This will be fixed in the next release @budgester

**Comment by brentm5** [comment]
Closing this as v0.12.0 was released today.

**Comment by budgester** [comment]
Nice
