### ISSUE TITLE
Configure option on Tentacle always skipped due to not_if

### ISSUE THREAD

**Issue by jeroendekorte** [cvent/octopus-deploy-cookbook#99]
Hi, looks like the tentacle configure option is always skipped due to the fact that the windows service is already created before this. Or am I doing something wrong here? 
Love to fix this  with another check not_if check if this is actually the case.

Regards,
Jeroen

**Comment by brentm5** [comment]
@jeroendekorte I think I need more information about what you are doing.  Can you provide the cookbook version you are using, the chef-client version you are using, and the code snippet of your tentacle resource (keeping in mind to remove anything sensitive).

Based on our own use internally I do not have this same issue.  Also the service does not get installed until this step (which is part of the configure step):

https://github.com/cvent/octopus-deploy-cookbook/blob/master/resources/tentacle.rb#L119

Also you can see this working in our integration tests here:

https://ci.appveyor.com/project/bigbam505/octopus-deploy-cookbook/build/1.0.188#L376

**Comment by brentm5** [comment]
Closing this because of lack of information.  Feel free to open this up again if you are still having the issue.
